name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Create build directory
      run: mkdir -p build

    - name: Configure CMake
      working-directory: ./build
      run: cmake ..

    - name: Build
      working-directory: ./build
      run: cmake --build . --config Release

    - name: Run tests
      working-directory: ./build
      run: |
        ./hello_world
        echo "1 3 -4" | ./solver_app
